/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.takmicenje;

import forme.*;
import kontroler.Kontroler;
import domain.Takmicenje;
import domain.Ucesce;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import forme.model.TableModelTakmicenje;

/**
 *
 * @author Bojana
 */
public class FrmPretrazivanjeTakmicenja extends javax.swing.JDialog {

    /**
     * Creates new form FormaPretrazivanjeKlizaca
     */
    public FrmPretrazivanjeTakmicenja(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        btnPronadji.setVisible(true);
        lblOdaberi.setVisible(false);
        setLocationRelativeTo(null);
        prikaziTabeluTakmicenja();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        panelBackground = new javax.swing.JPanel();
        lblPretragaTakmicenja = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTakmicenje = new javax.swing.JTable();
        btnPronadji = new javax.swing.JButton();
        panelMenu = new javax.swing.JPanel();
        lblPovratakNaGlavniMeni = new javax.swing.JLabel();
        filter = new javax.swing.JCheckBox();
        datumOd = new com.toedter.calendar.JDateChooser();
        datumDo = new com.toedter.calendar.JDateChooser();
        lblPretragaTakmicenja1 = new javax.swing.JLabel();
        lblPretragaTakmicenja2 = new javax.swing.JLabel();
        txtPoruka = new javax.swing.JLabel();
        lblOdaberi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        panelBackground.setBackground(new java.awt.Color(255, 255, 255));

        lblPretragaTakmicenja.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblPretragaTakmicenja.setForeground(new java.awt.Color(51, 51, 51));
        lblPretragaTakmicenja.setText("Unesite period održavanja takmičenja: ");

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        tblTakmicenje.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTakmicenje);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 826, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnPronadji.setBackground(new java.awt.Color(51, 51, 51));
        btnPronadji.setForeground(new java.awt.Color(255, 255, 255));
        btnPronadji.setText("Pronađi takmičenje");
        btnPronadji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPronadjiActionPerformed(evt);
            }
        });

        panelMenu.setBackground(new java.awt.Color(153, 153, 153));

        lblPovratakNaGlavniMeni.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblPovratakNaGlavniMeni.setForeground(new java.awt.Color(255, 255, 255));
        lblPovratakNaGlavniMeni.setText("[Povratak na glavnu formu]");
        lblPovratakNaGlavniMeni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPovratakNaGlavniMeniMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblPovratakNaGlavniMeni)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(lblPovratakNaGlavniMeni)
                .addGap(22, 22, 22))
        );

        filter.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        filter.setForeground(new java.awt.Color(51, 51, 51));
        filter.setText("Fiter");
        filter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterActionPerformed(evt);
            }
        });

        datumOd.setDateFormatString("yyyy-MM-dd");

        datumDo.setDateFormatString("yyyy-MM-dd");

        lblPretragaTakmicenja1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblPretragaTakmicenja1.setForeground(new java.awt.Color(51, 51, 51));
        lblPretragaTakmicenja1.setText("Datum od: ");

        lblPretragaTakmicenja2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblPretragaTakmicenja2.setForeground(new java.awt.Color(51, 51, 51));
        lblPretragaTakmicenja2.setText("Datum do: ");

        txtPoruka.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtPoruka.setForeground(new java.awt.Color(0, 0, 153));

        lblOdaberi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblOdaberi.setForeground(new java.awt.Color(0, 51, 153));
        lblOdaberi.setText("Odaberite takmicenje iz liste");

        javax.swing.GroupLayout panelBackgroundLayout = new javax.swing.GroupLayout(panelBackground);
        panelBackground.setLayout(panelBackgroundLayout);
        panelBackgroundLayout.setHorizontalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelBackgroundLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOdaberi)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelBackgroundLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelBackgroundLayout.createSequentialGroup()
                                .addComponent(lblPretragaTakmicenja1)
                                .addGap(18, 18, 18)
                                .addComponent(datumOd, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(lblPretragaTakmicenja2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(datumDo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(filter))
                            .addComponent(lblPretragaTakmicenja)
                            .addComponent(txtPoruka))))
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBackgroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPronadji, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(316, 316, 316))
        );
        panelBackgroundLayout.setVerticalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackgroundLayout.createSequentialGroup()
                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPoruka)
                .addGap(9, 9, 9)
                .addComponent(lblPretragaTakmicenja)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBackgroundLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(lblPretragaTakmicenja1))
                    .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(datumDo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(datumOd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPretragaTakmicenja2, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(filter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(lblOdaberi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnPronadji, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPronadjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPronadjiActionPerformed

        int odabraniRed = tblTakmicenje.getSelectedRow();

        if (odabraniRed == -1) {
            JOptionPane.showMessageDialog(this, "Morate odabrati red!");
            return;
        }

        String naziv = (String) tblTakmicenje.getValueAt(odabraniRed, 0);

        JOptionPane.showMessageDialog(this,
                "Naziv takmičenja: " + naziv, "Poruka",
                JOptionPane.INFORMATION_MESSAGE);

        List<Takmicenje> takmicenja = Kontroler.getInstance().ucitajTakmicenja();

        for (Takmicenje t : takmicenja) {
            if (t.getNaziv().equals(naziv)) {
                Kontroler.getInstance().setTakmicenje(t);
                this.dispose();
                
                
                ArrayList<Ucesce> ucesca 
                        = (ArrayList<Ucesce>) Kontroler.getInstance().vratiUcescaNaTakmicenju(t);
                t.setUcesca(ucesca);
                
                // Unos novog ucesca ili unos rezultata za postojece i odredjivanje plasmana
                
                if (t.getUcesca().isEmpty()) {
                    
                    FrmKreirajTakmicenje fk
                            = new FrmKreirajTakmicenje(FormMode.VIDI_TAKMICENJE);
                    fk.vidiTakmicenje(t);
                    fk.setLocationRelativeTo(null);
                    fk.setVisible(true);
                } else {
                    
                    FrmKreirajTakmicenje fk
                            = new FrmKreirajTakmicenje(FormMode.UNESI_REZULTATE);
                    fk.unesiRezultateZaTakmicenje(t);
                    fk.setLocationRelativeTo(null);
                    fk.setVisible(true);
                }
                return;
            }
        }

        FrmKreirajTakmicenje form = new FrmKreirajTakmicenje(FormMode.VIDI_TAKMICENJE);
        form.setLocationRelativeTo(null);
        form.setVisible(true);

    }//GEN-LAST:event_btnPronadjiActionPerformed

    private void lblPovratakNaGlavniMeniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPovratakNaGlavniMeniMouseClicked

        new FormMain().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_lblPovratakNaGlavniMeniMouseClicked

    private void filterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterActionPerformed
        filtrirajPoDatumu();
    }//GEN-LAST:event_filterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPronadji;
    private com.toedter.calendar.JDateChooser datumDo;
    private com.toedter.calendar.JDateChooser datumOd;
    private javax.swing.JCheckBox filter;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblOdaberi;
    private javax.swing.JLabel lblPovratakNaGlavniMeni;
    private javax.swing.JLabel lblPretragaTakmicenja;
    private javax.swing.JLabel lblPretragaTakmicenja1;
    private javax.swing.JLabel lblPretragaTakmicenja2;
    private javax.swing.JPanel panelBackground;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JTable tblTakmicenje;
    private javax.swing.JLabel txtPoruka;
    // End of variables declaration//GEN-END:variables

    private void prikaziTabeluTakmicenja() {

        ArrayList<Takmicenje> takmicenja = (ArrayList<Takmicenje>) Kontroler.getInstance().ucitajTakmicenja();
        TableModelTakmicenje tmt = new TableModelTakmicenje(takmicenja);
        tblTakmicenje.setModel(tmt);

    }

    public void filtrirajPoDatumu() {

        Date datOd = this.datumOd.getDate();
        Date datDo = this.datumDo.getDate();

        if (datOd == null || datDo == null) {
            JOptionPane.showMessageDialog(this, "Odaberite datum!!");
            return;
        }

        Takmicenje t = new Takmicenje();
        t.setPocetak(datOd);
        t.setKraj(datDo);

        txtPoruka.setVisible(false);
        lblOdaberi.setVisible(false);

        if (filter.isSelected()) {

            if (datOd.after(datDo)) {
                JOptionPane.showMessageDialog(this, "Datum početka mora biti pre datuma kraja!");
                return;
            }
   
            ArrayList<Takmicenje> takmicenja = Kontroler.getInstance().ucitajTakmicenja(t);
            TableModelTakmicenje tmt = new TableModelTakmicenje(takmicenja);
            tblTakmicenje.setModel(tmt);;
            lblOdaberi.setVisible(false);
            txtPoruka.setVisible(false);

            if (takmicenja.size() < 1) {
                txtPoruka.setVisible(true);
                txtPoruka.setText("Sistem ne može da nađe takmičenja po zadatoj vrednosti!");
                return;
            } else {
                // btnPronadji.setVisible(true);
                lblOdaberi.setVisible(true);
                lblOdaberi.setText("Odaberite takmičenje iz liste!");
                txtPoruka.setVisible(true);
                txtPoruka.setText("Sistem je našao takmičenja po zadatoj vrednosti!");
                return;
            }
        } else {

            List<Takmicenje> takmicenja = Kontroler.getInstance().ucitajTakmicenja();
            TableModelTakmicenje tmt = new TableModelTakmicenje(takmicenja);
            tblTakmicenje.setModel(tmt);
        }
    }

}
