/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import kontroler.Kontroler;
import transfer.util.UcitajParametreZaKonekciju;
import transfer.util.Util;

/**
 *
 * @author Bojana
 */
public class FrmKonekcija extends javax.swing.JDialog {

    /**
     * Creates new form FrmKonekcija
     */
    public FrmKonekcija(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        postavi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        PanelPozadina = new javax.swing.JPanel();
        txtIPadresa = new javax.swing.JTextField();
        txtBrojPorta = new javax.swing.JTextField();
        lblIPAdresa = new javax.swing.JLabel();
        lblBrojPorta = new javax.swing.JLabel();
        btnPokreni = new javax.swing.JButton();
        lblGornjiLeviUgao = new javax.swing.JLabel();
        lblDonjiDesniUgao = new javax.swing.JLabel();
        lblDonjiLeviUgao = new javax.swing.JLabel();
        lblGornjiDesniUgao = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        PanelPozadina.setBackground(new java.awt.Color(255, 255, 255));
        PanelPozadina.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 3));

        txtIPadresa.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));

        txtBrojPorta.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));

        lblIPAdresa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblIPAdresa.setForeground(new java.awt.Color(51, 51, 51));
        lblIPAdresa.setText("IP adresa: ");

        lblBrojPorta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblBrojPorta.setForeground(new java.awt.Color(51, 51, 51));
        lblBrojPorta.setText("Broj porta: ");

        btnPokreni.setBackground(new java.awt.Color(51, 51, 51));
        btnPokreni.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnPokreni.setForeground(new java.awt.Color(255, 255, 255));
        btnPokreni.setText("Pokreni");
        btnPokreni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPokreniActionPerformed(evt);
            }
        });

        lblGornjiLeviUgao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/form/img/little_snowflake.png"))); // NOI18N

        lblDonjiDesniUgao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/form/img/little_snowflake.png"))); // NOI18N

        lblDonjiLeviUgao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/form/img/little_snowflake.png"))); // NOI18N

        lblGornjiDesniUgao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/form/img/little_snowflake.png"))); // NOI18N

        javax.swing.GroupLayout PanelPozadinaLayout = new javax.swing.GroupLayout(PanelPozadina);
        PanelPozadina.setLayout(PanelPozadinaLayout);
        PanelPozadinaLayout.setHorizontalGroup(
            PanelPozadinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPozadinaLayout.createSequentialGroup()
                .addGroup(PanelPozadinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPozadinaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblDonjiLeviUgao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblDonjiDesniUgao))
                    .addGroup(PanelPozadinaLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(PanelPozadinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnPokreni, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelPozadinaLayout.createSequentialGroup()
                                .addGroup(PanelPozadinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPozadinaLayout.createSequentialGroup()
                                        .addComponent(lblBrojPorta)
                                        .addGap(18, 18, 18))
                                    .addGroup(PanelPozadinaLayout.createSequentialGroup()
                                        .addComponent(lblIPAdresa)
                                        .addGap(22, 22, 22)))
                                .addGroup(PanelPozadinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(PanelPozadinaLayout.createSequentialGroup()
                                        .addComponent(txtIPadresa)
                                        .addGap(4, 4, 4))
                                    .addComponent(txtBrojPorta, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 22, Short.MAX_VALUE))
                    .addGroup(PanelPozadinaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblGornjiLeviUgao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblGornjiDesniUgao)))
                .addContainerGap())
        );
        PanelPozadinaLayout.setVerticalGroup(
            PanelPozadinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPozadinaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelPozadinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGornjiLeviUgao)
                    .addComponent(lblGornjiDesniUgao))
                .addGap(51, 51, 51)
                .addGroup(PanelPozadinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIPAdresa, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtIPadresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelPozadinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBrojPorta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBrojPorta))
                .addGap(18, 18, 18)
                .addComponent(btnPokreni)
                .addGap(8, 8, 8)
                .addGroup(PanelPozadinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDonjiDesniUgao)
                    .addComponent(lblDonjiLeviUgao))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelPozadina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(PanelPozadina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPokreniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPokreniActionPerformed
        
        this.dispose();
        
        FrmPokretanjeServera frm = new FrmPokretanjeServera();
        frm.setVisible(true);
        frm.sakrijDugme();
        
        int broj = Integer.parseInt(txtBrojPorta.getText());
        Kontroler.getInstance().pokreniServer(broj);


    }//GEN-LAST:event_btnPokreniActionPerformed

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPozadina;
    private javax.swing.JButton btnPokreni;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel lblBrojPorta;
    private javax.swing.JLabel lblDonjiDesniUgao;
    private javax.swing.JLabel lblDonjiLeviUgao;
    private javax.swing.JLabel lblGornjiDesniUgao;
    private javax.swing.JLabel lblGornjiLeviUgao;
    private javax.swing.JLabel lblIPAdresa;
    private javax.swing.JTextField txtBrojPorta;
    private javax.swing.JTextField txtIPadresa;
    // End of variables declaration//GEN-END:variables

    private void postavi() {
        setLocationRelativeTo(null);
        txtIPadresa.setEditable(false);
        txtBrojPorta.setEditable(true);
        txtIPadresa.setText(UcitajParametreZaKonekciju.getInstanca().vratiVrednostZaKljuc(Util.IP_ADRESA));
        txtBrojPorta.setText(UcitajParametreZaKonekciju.getInstanca().vratiVrednostZaKljuc(Util.BROJ_PORTA));
    }

}
