/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domain.Korisnik;
import forme.klizac.FormaKreirajKlizaca;
import forme.klizac.FormaPretrazivanjeKlizaca;
import forme.takmicenje.FrmKreirajTakmicenje;
import forme.takmicenje.FrmPretrazivanjeTakmicenja;
import java.io.IOException;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import konekcija.Komunikacija;
import transfer.TransferObjekatOdgovor;
import transfer.TransferObjekatZahtev;
import transfer.util.Session;
import transfer.util.Util;
import usecase.UseCase;

/**
 *
 * @author Bojana
 */
public class FormMain extends javax.swing.JFrame {

    public FormMain() {
        initComponents();
        populateCurrentUser();
        try {
            Komunikacija.getInstanca().setGlavnaForma(this);
        } catch (IOException ex) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jPanel1 = new javax.swing.JPanel();
        panelUser = new javax.swing.JPanel();
        lblTrenutniKorisnik = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        panelCitat = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        checkbox1 = new java.awt.Checkbox();
        jmbMainMenu = new javax.swing.JMenuBar();
        jmTakmicenja = new javax.swing.JMenu();
        jmiKreiranjeTakmicenja = new javax.swing.JMenuItem();
        jmiPretrazivanjeTakmicenja = new javax.swing.JMenuItem();
        jmKlizaci = new javax.swing.JMenu();
        jmiKreiranjeKlizaca = new javax.swing.JMenuItem();
        jmiPretrazivanjeKlizaca = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jmOdjaviSe = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        jMenuItem2.setText("jMenuItem2");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        panelUser.setBackground(new java.awt.Color(102, 102, 102));
        panelUser.setForeground(new java.awt.Color(255, 255, 255));
        panelUser.setAutoscrolls(true);

        lblTrenutniKorisnik.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTrenutniKorisnik.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forme/img/user.png"))); // NOI18N

        javax.swing.GroupLayout panelUserLayout = new javax.swing.GroupLayout(panelUser);
        panelUser.setLayout(panelUserLayout);
        panelUserLayout.setHorizontalGroup(
            panelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTrenutniKorisnik, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelUserLayout.setVerticalGroup(
            panelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUserLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(panelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUserLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUserLayout.createSequentialGroup()
                        .addComponent(lblTrenutniKorisnik, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        panelUser.getAccessibleContext().setAccessibleName("");

        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jButton1.setText("jButton1");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jButton2.setText("jButton2");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel8.setFont(new java.awt.Font("Bookman Old Style", 2, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("“");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel5.setFont(new java.awt.Font("Lucida Calligraphy", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("variation or another thing to learn, and that's what I liked ");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel4.setFont(new java.awt.Font("Lucida Calligraphy", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("In skating there's always another jump or another spin ");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel6.setFont(new java.awt.Font("Lucida Calligraphy", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("about it. ");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel3.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Gracie Gold");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout panelCitatLayout = new javax.swing.GroupLayout(panelCitat);
        panelCitat.setLayout(panelCitatLayout);
        panelCitatLayout.setHorizontalGroup(
            panelCitatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCitatLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 793, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCitatLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelCitatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCitatLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCitatLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(57, 57, 57))))
            .addGroup(panelCitatLayout.createSequentialGroup()
                .addGroup(panelCitatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCitatLayout.createSequentialGroup()
                        .addGap(384, 384, 384)
                        .addComponent(jLabel6))
                    .addGroup(panelCitatLayout.createSequentialGroup()
                        .addGap(426, 426, 426)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCitatLayout.setVerticalGroup(
            panelCitatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCitatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(3, 3, 3)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(9, 9, 9))
        );

        jLabel8.getAccessibleContext().setAccessibleName("");
        jLabel5.getAccessibleContext().setAccessibleName("");
        jLabel4.getAccessibleContext().setAccessibleName("");
        jLabel6.getAccessibleContext().setAccessibleName("");
        jLabel3.getAccessibleContext().setAccessibleName("");

        checkbox1.setLabel("checkbox1");

        jmbMainMenu.setBackground(new java.awt.Color(102, 102, 102));
        jmbMainMenu.setForeground(new java.awt.Color(102, 102, 102));
        jmbMainMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jmbMainMenu.setPreferredSize(new java.awt.Dimension(110, 70));

        jmTakmicenja.setBackground(new java.awt.Color(102, 102, 102));
        jmTakmicenja.setForeground(new java.awt.Color(255, 255, 255));
        jmTakmicenja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forme/img/klizaljke.png"))); // NOI18N
        jmTakmicenja.setText("Takmičenja  ");
        jmTakmicenja.setPreferredSize(new java.awt.Dimension(200, 64));

        jmiKreiranjeTakmicenja.setBackground(new java.awt.Color(255, 255, 255));
        jmiKreiranjeTakmicenja.setForeground(new java.awt.Color(102, 102, 102));
        jmiKreiranjeTakmicenja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forme/img/little_snowflake.png"))); // NOI18N
        jmiKreiranjeTakmicenja.setText("Kreiranje takmičenja");
        jmiKreiranjeTakmicenja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiKreiranjeTakmicenjaActionPerformed(evt);
            }
        });
        jmTakmicenja.add(jmiKreiranjeTakmicenja);

        jmiPretrazivanjeTakmicenja.setBackground(new java.awt.Color(255, 255, 255));
        jmiPretrazivanjeTakmicenja.setForeground(new java.awt.Color(102, 102, 102));
        jmiPretrazivanjeTakmicenja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forme/img/little_snowflake.png"))); // NOI18N
        jmiPretrazivanjeTakmicenja.setText("Pretraživanje takmičenja");
        jmiPretrazivanjeTakmicenja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPretrazivanjeTakmicenjaActionPerformed(evt);
            }
        });
        jmTakmicenja.add(jmiPretrazivanjeTakmicenja);

        jmbMainMenu.add(jmTakmicenja);
        jmTakmicenja.getAccessibleContext().setAccessibleName("");

        jmKlizaci.setBackground(new java.awt.Color(255, 255, 255));
        jmKlizaci.setForeground(new java.awt.Color(255, 255, 255));
        jmKlizaci.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forme/img/skating.png"))); // NOI18N
        jmKlizaci.setText("Klizači   ");
        jmKlizaci.setPreferredSize(new java.awt.Dimension(200, 64));

        jmiKreiranjeKlizaca.setBackground(new java.awt.Color(255, 255, 255));
        jmiKreiranjeKlizaca.setForeground(new java.awt.Color(102, 102, 102));
        jmiKreiranjeKlizaca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forme/img/little_snowflake.png"))); // NOI18N
        jmiKreiranjeKlizaca.setText("Kreiranje klizača");
        jmiKreiranjeKlizaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiKreiranjeKlizacaActionPerformed(evt);
            }
        });
        jmKlizaci.add(jmiKreiranjeKlizaca);

        jmiPretrazivanjeKlizaca.setBackground(new java.awt.Color(255, 255, 255));
        jmiPretrazivanjeKlizaca.setForeground(new java.awt.Color(102, 102, 102));
        jmiPretrazivanjeKlizaca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forme/img/little_snowflake.png"))); // NOI18N
        jmiPretrazivanjeKlizaca.setText("Pretraživanje klizača");
        jmiPretrazivanjeKlizaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPretrazivanjeKlizacaActionPerformed(evt);
            }
        });
        jmKlizaci.add(jmiPretrazivanjeKlizaca);

        jmbMainMenu.add(jmKlizaci);
        jmKlizaci.getAccessibleContext().setAccessibleName("");

        jMenu6.setText("                                                                                                                                                                                                                                                                                                                                                                  ");
        jMenu6.setEnabled(false);
        jmbMainMenu.add(jMenu6);
        jMenu6.getAccessibleContext().setAccessibleName("");

        jmOdjaviSe.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        jmOdjaviSe.setForeground(new java.awt.Color(255, 255, 255));
        jmOdjaviSe.setText("          Odjavi se                            ");
        jmOdjaviSe.setPreferredSize(new java.awt.Dimension(220, 20));
        jmOdjaviSe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmOdjaviSeMouseClicked(evt);
            }
        });
        jmbMainMenu.add(jmOdjaviSe);
        jmOdjaviSe.getAccessibleContext().setAccessibleName("");

        setJMenuBar(jmbMainMenu);
        jmbMainMenu.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(40, 40, 40)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCitat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(297, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(279, 279, 279))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(panelCitat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(260, 260, 260))))
        );

        jPanel1.getAccessibleContext().setAccessibleName("");
        jButton1.getAccessibleContext().setAccessibleName("");
        jButton2.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiKreiranjeTakmicenjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiKreiranjeTakmicenjaActionPerformed
        FrmKreirajTakmicenje fkt = new FrmKreirajTakmicenje(FormMode.KREIRAJ_TAKMICENJE);
        fkt.setLocationRelativeTo(null);
        fkt.pack();
        fkt.setVisible(true);
    }//GEN-LAST:event_jmiKreiranjeTakmicenjaActionPerformed

    private void jmiPretrazivanjeTakmicenjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPretrazivanjeTakmicenjaActionPerformed
        FrmPretrazivanjeTakmicenja fmt
                = new FrmPretrazivanjeTakmicenja(null, true);
        fmt.pack();
        fmt.setLocationRelativeTo(null);
        fmt.setVisible(true);
    }//GEN-LAST:event_jmiPretrazivanjeTakmicenjaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void jmiKreiranjeKlizacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiKreiranjeKlizacaActionPerformed
        JDialog formKreirajKlizaca
                = new FormaKreirajKlizaca(null, true, FormMode.KREIRAJ_KLIZACA);
        formKreirajKlizaca.setLocationRelativeTo(null);
        formKreirajKlizaca.setVisible(true);
        Session.getInstance().setCurrentUseCase(UseCase.UC_KREIRAJ_KLIZACA);
    }//GEN-LAST:event_jmiKreiranjeKlizacaActionPerformed

    private void jmiPretrazivanjeKlizacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPretrazivanjeKlizacaActionPerformed
        JDialog formPretrazivanjeKlizaca
                = new FormaPretrazivanjeKlizaca(null, true, FormMode.PRETRAZIVANJE_KLIZACA);
        formPretrazivanjeKlizaca.setLocationRelativeTo(null);
        formPretrazivanjeKlizaca.setVisible(true);
        Session.getInstance().setCurrentUseCase(UseCase.UC_PRETRAZIVANJE_KLIZACA);
    }//GEN-LAST:event_jmiPretrazivanjeKlizacaActionPerformed

    private void jmOdjaviSeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmOdjaviSeMouseClicked
        int rezultat = JOptionPane.showConfirmDialog(this, "Da li zaista želite "
                + "da se odjavite?",
                "Pitanje", JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        if (rezultat == JOptionPane.YES_OPTION) {
            odjaviKorisnika();
            this.dispose();
            (new FormLogIn()).setVisible(true);
        }
    }//GEN-LAST:event_jmOdjaviSeMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Checkbox checkbox1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JMenu jmKlizaci;
    private javax.swing.JMenu jmOdjaviSe;
    private javax.swing.JMenu jmTakmicenja;
    private javax.swing.JMenuBar jmbMainMenu;
    private javax.swing.JMenuItem jmiKreiranjeKlizaca;
    private javax.swing.JMenuItem jmiKreiranjeTakmicenja;
    private javax.swing.JMenuItem jmiPretrazivanjeKlizaca;
    private javax.swing.JMenuItem jmiPretrazivanjeTakmicenja;
    private javax.swing.JLabel lblTrenutniKorisnik;
    private javax.swing.JPanel panelCitat;
    private javax.swing.JPanel panelUser;
    // End of variables declaration//GEN-END:variables

    private void populateCurrentUser() {
        Korisnik korisnik = Session.getInstance().getCurrentUser();
        lblTrenutniKorisnik.setText(korisnik.getIme() + " " + korisnik.getPrezime());
        jmOdjaviSe.setText("   Odjavi se " + korisnik.getKorisnickoIme() + "   ");
    }

    private void odjaviKorisnika() {
        try {
            TransferObjekatZahtev tz = new TransferObjekatZahtev();
            tz.setParametar(Session.getInstance().getCurrentUser());
            tz.setOperacija(Util.ODJAVI_SE);
            Komunikacija.getInstanca().posaljiZahtev(tz);
            TransferObjekatOdgovor too = Komunikacija.getInstanca().primiOdgovor();
            JOptionPane.showMessageDialog(this, "Uspesno ste se odjavili!");
            System.exit(0);
        } catch (Exception ex) {
            System.out.println("Greska: " + ex.getMessage());
        }
    }

}
