package forme;

import domain.Korisnik;
import java.io.IOException;
import java.net.Socket;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import konekcija.Komunikacija;
import kontroler.Kontroler;
import transfer.util.Session;

public class FormLogIn extends javax.swing.JFrame {

    Socket socket;

    public FormLogIn() {

        initComponents();
        getContentPane().setBackground(new java.awt.Color(255, 255, 255));
        try {
            Komunikacija.getInstanca().setFrm(this);
        } catch (IOException ex) {
            System.out.println("Soket je zatvoren...");
        }
        otvoriFormu();

    }

    private void otvoriFormu() {
        setTitle("Prijavljivanje");
        setVisible(true);
    }

    /*
    Before making the frame visible and after pack() is called, call this -

    this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    Assuming "this" is an instance of JFrame.
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelUser = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblKorisnickoIme = new javax.swing.JLabel();
        lblLozinka = new javax.swing.JLabel();
        txtKorisnickoIme = new javax.swing.JTextField();
        txtLozinka = new javax.swing.JPasswordField();
        btnPrijaviSe = new javax.swing.JButton();
        lblGreska = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        panelUser.setBackground(new java.awt.Color(102, 102, 102));
        panelUser.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forme/img/user.png"))); // NOI18N

        lblKorisnickoIme.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblKorisnickoIme.setForeground(new java.awt.Color(255, 255, 255));
        lblKorisnickoIme.setText("Korisničko ime:");

        lblLozinka.setBackground(new java.awt.Color(255, 255, 255));
        lblLozinka.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblLozinka.setForeground(new java.awt.Color(255, 255, 255));
        lblLozinka.setText("Lozinka:");

        txtKorisnickoIme.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 114, 135)));
        txtKorisnickoIme.setSelectionColor(new java.awt.Color(102, 102, 102));

        txtLozinka.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 114, 135)));
        txtLozinka.setSelectionColor(new java.awt.Color(102, 102, 102));

        btnPrijaviSe.setBackground(new java.awt.Color(255, 255, 255));
        btnPrijaviSe.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnPrijaviSe.setText("Prijavite se");
        btnPrijaviSe.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btnPrijaviSe.setPreferredSize(new java.awt.Dimension(63, 25));
        btnPrijaviSe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrijaviSeActionPerformed(evt);
            }
        });

        lblGreska.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelUserLayout = new javax.swing.GroupLayout(panelUser);
        panelUser.setLayout(panelUserLayout);
        panelUserLayout.setHorizontalGroup(
            panelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUserLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(panelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelUserLayout.createSequentialGroup()
                        .addComponent(lblLozinka, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPrijaviSe, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLozinka, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelUserLayout.createSequentialGroup()
                        .addComponent(lblKorisnickoIme, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtKorisnickoIme, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblGreska, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        panelUserLayout.setVerticalGroup(
            panelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUserLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(panelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKorisnickoIme)
                    .addComponent(txtKorisnickoIme, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLozinka, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLozinka))
                .addGap(18, 18, 18)
                .addComponent(btnPrijaviSe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lblGreska, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    int brojPokusajaPrijavljivanja = 3;

    private void btnPrijaviSeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrijaviSeActionPerformed

        if (brojPokusajaPrijavljivanja < 1) {

            txtKorisnickoIme.setEnabled(false);
            txtLozinka.setEnabled(false);
            btnPrijaviSe.setEnabled(false);
            JOptionPane.showMessageDialog(this, "Ne možete se prijaviti na sistem!",
                    "Poruka", JOptionPane.ERROR_MESSAGE);
            return;

        }

        String korisnickoIme = txtKorisnickoIme.getText();
        String lozinka = new String(txtLozinka.getPassword());

        if (!korisnickoIme.isEmpty() && !lozinka.isEmpty()) {

            Korisnik k = new Korisnik();
            k.setKorisnickoIme(korisnickoIme);
            k.setLozinka(lozinka);

            Korisnik korisnik
                    = Kontroler.getInstance().ProveriPodatke(k);

            if (korisnik == null) {
                brojPokusajaPrijavljivanja--;
                lblGreska.setText("Preostalo pokušaja prijavljivanja: " + brojPokusajaPrijavljivanja);
                JOptionPane.showMessageDialog(this, "Neuspešno prijavljivanje na sistem!",
                        "Poruka", JOptionPane.WARNING_MESSAGE);
                return;
            } else {
                Session.getInstance().setCurrentUser(korisnik);
                JOptionPane.showMessageDialog(this, "Uspešno ste se prijavili na sistem!",
                        "Uspešno prijavljivanje!",
                        JOptionPane.INFORMATION_MESSAGE);

                JFrame formaGlavna = new FormMain();
                this.setVisible(false);
                this.setLocationRelativeTo(null);
                formaGlavna.setVisible(true);
            }
        } else {
            brojPokusajaPrijavljivanja--;
            lblGreska.setText("Preostalo pokušaja prijavljivanja: " + brojPokusajaPrijavljivanja);
            JOptionPane.showMessageDialog(this, "Neuspešno prijavljivanje na sistem!",
                    "Poruka", JOptionPane.WARNING_MESSAGE);
            return;
        }

    }//GEN-LAST:event_btnPrijaviSeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrijaviSe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblGreska;
    private javax.swing.JLabel lblKorisnickoIme;
    private javax.swing.JLabel lblLozinka;
    private javax.swing.JPanel panelUser;
    private javax.swing.JTextField txtKorisnickoIme;
    private javax.swing.JPasswordField txtLozinka;
    // End of variables declaration//GEN-END:variables

}
