/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.klizac;

import domain.Drzava;
import domain.EnumPol;
import kontroler.Kontroler;
import domain.Klizac;
import forme.FormMain;
import forme.FormMode;
import forme.takmicenje.FrmKreirajTakmicenje;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import konekcija.Komunikacija;
import transfer.util.Session;
import forme.model.TableModelKlizac;
import transfer.TransferObjekatOdgovor;
import transfer.TransferObjekatZahtev;
import transfer.util.EnumStatus;
import usecase.UseCase;
import transfer.util.Util;

/**
 *
 * @author Bojana
 */
public class FormaPretrazivanjeKlizaca extends javax.swing.JDialog {

    /**
     * Creates new form FormaPretrazivanjeKlizaca
     */
    FormMode formMode;
    // NitOsvezavanjePrikazaKlizaca nit = new NitOsvezavanjePrikazaKlizaca(this);

    public FormaPretrazivanjeKlizaca(javax.swing.JFrame parent, boolean modal,
            FormMode formMode) {
        super(parent, modal);
        initComponents();
        sakrijDugme();
        prikaziTabeluKlizaca();
        setLocationRelativeTo(null);
        // Kontroler.getInstance().setFrmPretragaKlizaca(this);
        postaviFormu(formMode);
        //    nit.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        panelBackground = new javax.swing.JPanel();
        txtOdabirKliazaca = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKlizaci = new javax.swing.JTable();
        btnDetalji = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblPovratakNaGlavniMeni = new javax.swing.JLabel();
        btnDodaj = new javax.swing.JButton();
        filterPrezime = new javax.swing.JCheckBox();
        txtPrezime = new javax.swing.JTextField();
        lblPoruka = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        panelBackground.setBackground(new java.awt.Color(255, 255, 255));

        txtOdabirKliazaca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtOdabirKliazaca.setForeground(new java.awt.Color(51, 51, 51));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        tblKlizaci.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblKlizaci);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnDetalji.setBackground(new java.awt.Color(51, 51, 51));
        btnDetalji.setForeground(new java.awt.Color(255, 255, 255));
        btnDetalji.setText("Pronađi klizača");
        btnDetalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetaljiActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        lblPovratakNaGlavniMeni.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblPovratakNaGlavniMeni.setForeground(new java.awt.Color(255, 255, 255));
        lblPovratakNaGlavniMeni.setText("[Povratak na glavnu formu]");
        lblPovratakNaGlavniMeni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPovratakNaGlavniMeniMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblPovratakNaGlavniMeni)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(lblPovratakNaGlavniMeni)
                .addGap(22, 22, 22))
        );

        btnDodaj.setBackground(new java.awt.Color(51, 51, 51));
        btnDodaj.setForeground(new java.awt.Color(255, 255, 255));
        btnDodaj.setText("+");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        filterPrezime.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        filterPrezime.setForeground(new java.awt.Color(51, 51, 51));
        filterPrezime.setText("Filtriraj po početnom slovu prezimena");
        filterPrezime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterPrezimeActionPerformed(evt);
            }
        });

        lblPoruka.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblPoruka.setForeground(new java.awt.Color(0, 0, 153));

        javax.swing.GroupLayout panelBackgroundLayout = new javax.swing.GroupLayout(panelBackground);
        panelBackground.setLayout(panelBackgroundLayout);
        panelBackgroundLayout.setHorizontalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelBackgroundLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPoruka)
                    .addGroup(panelBackgroundLayout.createSequentialGroup()
                        .addComponent(filterPrezime)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOdabirKliazaca)
                        .addGap(31, 31, 31)
                        .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBackgroundLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(btnDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBackgroundLayout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(btnDetalji, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, Short.MAX_VALUE))
        );
        panelBackgroundLayout.setVerticalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackgroundLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPoruka)
                .addGap(4, 4, 4)
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOdabirKliazaca)
                    .addComponent(filterPrezime)
                    .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBackgroundLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBackgroundLayout.createSequentialGroup()
                        .addComponent(btnDodaj)
                        .addGap(132, 132, 132)))
                .addComponent(btnDetalji)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDetaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetaljiActionPerformed

        try {

            int odabraniRed = getSelectedRow();

            if (odabraniRed != -1) {

                String klizacID = (String) tblKlizaci.getValueAt(odabraniRed, 0);
                JOptionPane.showMessageDialog(this,
                        "ID odabranog klizača: " + klizacID, "Poruka",
                        JOptionPane.INFORMATION_MESSAGE);

                Session.getInstance().setCurrentUseCase(UseCase.UC_PRETRAZIVANJE_KLIZACA);
                Session.getInstance().getUseCaseParams().clear();
                Session.getInstance().getUseCaseParams().put("klizacID", klizacID);

                this.dispose();

                JDialog form
                        = new FormaKreirajKlizaca(null, true, FormMode.VIDI_KLIZACA);
                form.setLocationRelativeTo(null);
                form.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this,
                        "Odaberite red!", "Poruka",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Sistem ne može da prikaže klizača!", "Poruka",
                    JOptionPane.INFORMATION_MESSAGE);
            ex.printStackTrace();
        }

    }//GEN-LAST:event_btnDetaljiActionPerformed

    private void lblPovratakNaGlavniMeniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPovratakNaGlavniMeniMouseClicked
        new FormMain().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblPovratakNaGlavniMeniMouseClicked

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed

        postaviFormu(FormMode.DODAJ_UCESNIKE);

        int red = tblKlizaci.getSelectedRow();

        String id = (String) tblKlizaci.getValueAt(red, 0);
        String ime = (String) tblKlizaci.getValueAt(red, 1);
        String prezime = (String) tblKlizaci.getValueAt(red, 2);
        Date datum = (Date) tblKlizaci.getValueAt(red, 3);
        EnumPol pol = (EnumPol) tblKlizaci.getValueAt(red, 4);
        Drzava drzava = (Drzava) tblKlizaci.getValueAt(red, 5);

        Kontroler.getInstance().pronadjiDrzavu(drzava.getDrzavaID());

        Klizac k = new Klizac(id, ime, prezime, datum, pol, drzava);

        FrmKreirajTakmicenje topFrame = (FrmKreirajTakmicenje) getParent();

        topFrame.dodajKlizacaUTabeluUcesca(k);


    }//GEN-LAST:event_btnDodajActionPerformed

    private void filterPrezimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterPrezimeActionPerformed
        filtrirajPoPrezimenu();
    }//GEN-LAST:event_filterPrezimeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetalji;
    private javax.swing.JButton btnDodaj;
    private javax.swing.JCheckBox filterPrezime;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPoruka;
    private javax.swing.JLabel lblPovratakNaGlavniMeni;
    private javax.swing.JPanel panelBackground;
    private javax.swing.JTable tblKlizaci;
    private javax.swing.JLabel txtOdabirKliazaca;
    private javax.swing.JTextField txtPrezime;
    // End of variables declaration//GEN-END:variables

    private void prikaziTabeluKlizaca() {

        try {

            List<Klizac> klizaci = Kontroler.getInstance().dajSveKlizace();
            TableModelKlizac tm = new TableModelKlizac(klizaci);
            tblKlizaci.setModel(tm);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne može da učita listu klizača");
        }
    }

    private int getSelectedRow() {
        int selectedRow = tblKlizaci.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Niste odabrali red!",
                    "Poruka", JOptionPane.INFORMATION_MESSAGE);
        }
        return selectedRow;
    }

    public void obrisiKlizaca(Klizac klizac) throws Exception {

        TableModelKlizac tmk = (TableModelKlizac) tblKlizaci.getModel();
        TransferObjekatZahtev toz = new TransferObjekatZahtev();
        toz.setOperacija(Util.OPERACIJA_OBRISI_KLIZACA);
        toz.setParametar(klizac);
        Komunikacija.getInstanca().posaljiZahtev(toz);
        TransferObjekatOdgovor too = Komunikacija.getInstanca().primiOdgovor();
        if (too.getStatus() == EnumStatus.SVE_U_REDU) {
            JOptionPane.showMessageDialog(this,
                    "Sistem je obrisao klizača", "Poruka", JOptionPane.INFORMATION_MESSAGE);
            tmk.obrisiKlizaca(klizac);
        } else {
            JOptionPane.showMessageDialog(this,
                    "Sistem nije obrisao klizača", "Poruka", JOptionPane.INFORMATION_MESSAGE);
            tmk.obrisiKlizaca(klizac);
        }

    }

    private void postaviFormu(FormMode formMode) {

        switch (formMode) {
            case DODAJ_UCESNIKE:

                filterPrezime.setVisible(false);
                txtPrezime.setVisible(false);
                btnDetalji.setVisible(false);
                txtOdabirKliazaca.setText("Odaberite učesnike na takmičenju: ");
                btnDodaj.setVisible(true);
                break;

            case PRETRAZIVANJE_KLIZACA:
                btnDetalji.setVisible(false);
                filterPrezime.setVisible(true);
                txtPrezime.setVisible(true);
                btnDetalji.setVisible(true);
                txtOdabirKliazaca.setVisible(false);
                btnDodaj.setVisible(false);
                break;

        }
    }

    private void sakrijDugme() {
        btnDodaj.setVisible(false);
    }

    public void filtrirajPoPrezimenu() {

        String prezime = txtPrezime.getText();

        Klizac k = new Klizac();
        k.setPrezime(prezime);
        
        if (prezime.isEmpty() || prezime.length() > 1) {
            JOptionPane.showMessageDialog(this, "Unesite slovo!");
            return;
        }

        lblPoruka.setVisible(false);

        if (filterPrezime.isSelected()) {

            lblPoruka.setVisible(false);
            ArrayList<Klizac> klizaci = Kontroler.getInstance().vratiKlizace(k);
            TableModelKlizac tabela = new TableModelKlizac(klizaci);
            tblKlizaci.setModel(tabela);

            if (klizaci.size() < 1) {
                lblPoruka.setVisible(true);
                lblPoruka.setText("Sistem ne može da nađe klizače po zadatoj vrednosti!");
                return;
            } else {
                lblPoruka.setVisible(true);
                lblPoruka.setText("Sistem je našao klizače po zadatoj vrednosti!");
                return;
            }

        } else {

            List<Klizac> klizaci = Kontroler.getInstance().dajSveKlizace();
            TableModelKlizac tabela = new TableModelKlizac(klizaci);
            tblKlizaci.setModel(tabela);
        }
    }

}
